export const providerOrder = [
	'Stan',
	'Netflix',
	'ABC iview',
	'BINGE',
	'Foxtel',
	'Foxtel Now',
	'Paramount Plus',
	'Apple TV Plus',
	'Apple TV',
	'Amazon Prime Video',
	'Disney Plus',
	'SBS On Demand',
	'7plus',
	'9Now',
	'tenplay',
];